language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer selfupdate
  - composer install --dev
  - PHP_CURRENT='5.5'
  
script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - if [ $(phpenv version-name) = $PHP_CURRENT ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover --access-token=cfaf884e107457ef9d6fbba56b668d9bebd098e9797b01e0cf4950668232934c; fi
  - if [ $(phpenv version-name) = $PHP_CURRENT ]; then vendor/bin/phpcs --standard=./phpcs.xml -n --report=gitblame ./src; fi
  - if [ $(phpenv version-name) = $PHP_CURRENT ]; then vendor/bin/bugfree lint src/; fi

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

notifications:
  webhooks:
    urls:
      - http://derricks.io/repositories/buildhook/
    on_success: always
    on_failure: always
    on_start: true
